image: rbekker87/build-tools:latest

stages:
  - ver
  - deploy

ver:
  stage: ver
  script:
    - python --version
    - whoami


deploy_staging:
  stage: deploy
  script:
    - pip install psycopg2-binary
    - pip install -r requirements.txt
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/healthtrackerr.git
    - git push heroku master
    - echo "Deployed to Staging Server https://healthtrackerr.herokuapp.com"
  environment:
    name: staging
    url: https://healthtrackerr.herokuapp.com/
  only:
    - dev
